name: build

on:
  pull_request:
    paths:
      - .github/workflows/build.yaml
      - src/**
      - project/**
      - '*.sbt'
  push:
    branches:
      - main
    paths:
      - .github/workflows/build.yaml
      - src/**
      - project/**
      - '*.sbt'
  workflow_call:

jobs:
  sbt:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: temurin
          cache: sbt
      - run: sbt universal:packageBin
      - uses: actions/upload-artifact@v3
        with:
          name: gatling-build
          path: target/universal/gatling-latest.zip
          retention-days: 1
