name: loadtest

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
          key: sbt-v1-${{ hashFiles('build.sbt') }}
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - run: sbt universal:packageBin
      - uses: actions/upload-artifact@v2
        with:
          name: gatling-build
          path: target/universal/gatling-latest.zip
          retention-days: 1

  run:
    runs-on: ubuntu-latest
    needs:
      - build
    strategy:
      matrix:
        id: [1, 2, 3]
    env:
      SIMULATION_NAME: computerdatabase.BasicSimulation
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: actions/download-artifact@v2
      - run: unzip gatling-build/gatling-latest.zip
      - run: gatling-latest/bin/gatling.sh --no-reports -s "$SIMULATION_NAME"
      - uses: actions/upload-artifact@v2
        with:
          name: gatling-results-${{ matrix.id }}
          path: gatling-latest/results/
          retention-days: 1

  report:
    runs-on: ubuntu-latest
    needs:
      - run
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: actions/download-artifact@v2
      # copy logs to gatling-latest/results/gatling-results-...-simulation.log
      - run: |
          mkdir -p gatling-latest/results
          find gatling-results-* -name simulation.log | while read f; do
            cp -v "$f" "gatling-latest/results/${f//\//-}"
          done
      - run: unzip gatling-build/gatling-latest.zip
      - run: gatling-latest/bin/gatling.sh --reports-only .
      - uses: actions/upload-artifact@v2
        with:
          name: gatling-report
          path: gatling-latest/results/
