name: loadtest

on:
  workflow_call:
    inputs:
      simulation-classname:
        required: true
        type: string
        description: Classname of simulation to run
      runs-on:
        required: true
        type: string
        description: Gatling runner

jobs:
  build:
    uses: ./.github/workflows/build.yaml

  run:
    runs-on: ${{ inputs.runs-on }}
    timeout-minutes: 10
    needs:
      - build
    strategy:
      matrix:
        id: [1]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: temurin
      - uses: actions/download-artifact@v3
      - run: unzip gatling-build/gatling-latest.zip
      - uses: int128/comment-action@v1
        with:
          post: |
            :warning: Starting Gatling for simulation `${{ inputs.simulation-classname }}`
      - run: gatling-latest/bin/gatling.sh --no-reports -s '${{ inputs.simulation-classname }}'
      - uses: actions/upload-artifact@v3
        with:
          name: gatling-results-${{ matrix.id }}
          path: gatling-latest/results/
          retention-days: 1

  report:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs:
      - run
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: temurin
      - uses: actions/download-artifact@v3
      - name: Copy logs to gatling-latest/results/gatling-results-*-simulation.log
        run: |
          mkdir -p gatling-latest/results
          find gatling-results-* -name simulation.log | while read -r f; do
            cp -v "$f" "gatling-latest/results/${f//\//-}"
          done
      - run: unzip gatling-build/gatling-latest.zip
      - run: gatling-latest/bin/gatling.sh --reports-only .
      - uses: actions/upload-artifact@v3
        with:
          name: gatling-report
          path: gatling-latest/results/
      - uses: int128/comment-action@v1
        with:
          post: |
            :notebook: Gatling report is available in ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
