name: loadtest-example

on:
  pull_request:

jobs:
  run:
    if: startsWith(github.head_ref, 'example/')
    uses: ./.github/workflows/loadtest.yaml
    with:
      simulation-classname: example.ExampleSimulation
      runs-on: ubuntu-latest
