name: loadtest

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
          key: sbt-v1-${{ hashFiles('build.sbt') }}
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - run: sbt universal:packageBin
      - uses: actions/upload-artifact@v2
        with:
          name: gatling-zip
          path: target/universal/hello-gatling-latest.zip
          retention-days: 1

  run:
    runs-on: ubuntu-latest
    env:
      SIMULATION_NAME: computerdatabase.BasicSimulation
    needs:
      - build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: actions/download-artifact@v2
        with:
          name: gatling-zip
          path: target/universal/
      - run: make gatling
